### ISSUE TITLE
PP counter is either broken or only shows scoresaber pp

### ISSUE THREAD

**Issue by MCMODDER11** [Metalit/bsq-qounters-minus#2]
When using the pp counter, it shows an incorrect value. I am guessing that it is because it is pulling it from scoresaber. It's not necessarily a bug, it's just an issue for people who have beat leader and not scoresaber. A good addition would be either adding a value for beat leader and scoresaber like pc, or adding a switch for it. (Or both)

**Comment by HannesK-ME** [comment]
It's also broken for me. On any new song (that doesn't have a PB set) it shows a value about double of what it should be (19x%) and then when I replay that song the color never changes as the current score never gets any better than what's saved. This is on Quest 2 running 1.27.0

**Comment by Metalit** [comment]
You seem to have confused the P*B* qounter with the P*P* qounter lol. To respond to the original, I plan on adding beatleader PP in the future

**Comment by MCMODDER11** [comment]
k
