### ISSUE TITLE
FR: Support for NightscoutCounter

### ISSUE THREAD

**Issue by Arakon** [Metalit/bsq-qounters-minus#6]
https://github.com/legoandmars/NightscoutCounter adds the ability to use a Nightscout server to provide blood sugar readings for diabetics with a constant glucose monitor in the PC version of Counters+. This is incredibly useful to have, as it will allow you to keep an eye on your blood sugar while playing, which can drop dangerously fast while excercising.
I'm not sure how viable this is in the first place, but if this is a possibility, it would be awesome if this could be implemented.

**Comment by Metalit** [comment]
The mod already has an API for custom counters like this, such as my VisualScoreQounter, and I think this is definitely a case where it would belong as a separate mod. So anyone who wants to can use the API and port the counter, but I don't expect to do so myself
